spring.application.name=SpringAI-chatClient
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
